### ISSUE TITLE
TypeScript: Broken autofix for functions with `async` name

### ISSUE THREAD

**Issue by svr93** [lydell/eslint-plugin-simple-import-sort#17] opened 2019-07-07 12:08 UTC
I have noticed a strange behaviour that occurs with Angular testing library.
Before autofix:

```ts
import { TestBed, async } from '@angular/core/testing';
```
After autofix:

```ts
import { ,asyncTestBed } from '@angular/core/testing';
```

Package versions:
`eslint-plugin-simple-import-sort` -> 4.0.0
`@typescript-eslint/eslint-plugin` -> 1.10.2
`@typescript-eslint/parser` -> 1.10.2

`async` is not a reserved keyword - see https://www.ecma-international.org/ecma-262/10.0/index.html#sec-keywords

**Comment by lydell** [comment] 2019-07-07 12:36
Hi! Thanks for the issue!

I managed to reproduce your issue here: https://github.com/lydell/eslint-plugin-simple-import-issue

It seems like it only happens with in TypeScript.

I/we need to:

- Figure out what’s happening.
- See if it is an error in this plugin.
- See if it is an error in `@typescript-eslint/parser`, and if so, report it.
- See if there’s a workaround we can use in this plugin

Luckily, for now you can work around the problem by manually fixing the broken cases.

**Comment by svr93** [comment] 2019-07-07 14:59
@lydell Thank you!
The problem with `@typescript-eslint/typescript-estree` package.

I was able to reproduce it - https://github.com/typescript-eslint/typescript-eslint/issues/678

**Comment by lydell** [comment] 2019-07-08 16:15
I'm going to close this since https://github.com/typescript-eslint/typescript-eslint/pull/681 has been merged.

This will we on npm when the next version (after v1.11.0) of the `@typescript-eslint` packages are released.

**Closed by lydell** 2019-07-08 16:15 UTC
Labels: bug
