### ISSUE TITLE
Group node_module packages separately from from absolute project imports

### ISSUE THREAD

**Issue by mtjn** [lydell/eslint-plugin-simple-import-sort#29] opened 2019-11-13 16:15 UTC
In a sample app structure

```
node_modules
src
  util
  App.js
```

where `App.js` is:

```javascript
import React from "react";
import lib from "util/lib";

// code
```

Would it be possible to separate the two groups? Thanks!

**Comment by lydell** [comment] 2019-11-13 16:39
Duplicate of #18

**Closed by lydell** 2019-11-13 16:39 UTC

**Comment by lydell** [comment] 2019-11-22 17:45
This is now possible in v5.0.0 using
[custom grouping](https://github.com/lydell/eslint-plugin-simple-import-sort/tree/d1d59be47b08733990a8a62f7caf735cdad420f9#custom-grouping).

For example:

```json
{
  "rules": {
    "simple-import-sort/sort": [
      "error",
      {
        "groups": [["^\\u0000"], ["^@?\\w"], ["^util(/.*|$)"], ["^\\."]]
      }
    ]
  }
}
```
