### ISSUE TITLE
Plugin is trying to iterate html files

### ISSUE THREAD

**Issue by thebspin** [lydell/eslint-plugin-simple-import-sort#113] opened 2022-09-16 08:48 UTC
I am using nx ( https://nx.dev/ ) for having a monorepo in angular.
For checking our linting there is a nx plugin `@nrwl/linter:eslint` that checks all our ts and html files.
This is where the issues arrises...

```
Linting "bookingtool"...

 >  NX   programNode.body is not iterable

   Occurred while linting /Users/thebspin/dev/company/nx-repo/apps/bookingtool/src/app/app.component.html:1
   Rule: "simple-import-sort/imports"

TypeError: programNode.body is not iterable
Occurred while linting /Users/thebspin/dev/company/nx-repo/apps/bookingtool/src/app/app.component.html:1
```

This file is just angular html and should not be run by this plugin, or there should be an option to disable certain file types.
I tried setting an override in my eslint config to disable the rule when `"files": ["**/*.html"]` but no luck.

**Comment by lydell** [comment] 2022-09-16 10:04
Hi!

This is most likely a problem with your setup. This plugin has no knowledge of files. I just get an AST (Abstract Syntax Tree, source code parsed into objects) from ESLint and sort the imports in it. As far as I understand how ESLint plugins should work, I can just assume that the AST I get is for JavaScript and that it is in ESLint’s AST format.

What you need to do is try to create a reproduction repo (isolated from your real repo), and try to make it minimal. The problem might be in:

- Your config.
- `nx`
- `@nrwl/linter:eslint`
- or this plugin, if I’m making an assumption that doesn’t hold in certain circumstances

But right now we don’t know – you need to figure that out.

Myself I just use plain ESLint, so I’m not super keen on digging into the extra layers you have around it, but if you need help with this debugging – feel free ask and I might be able to help, but I can’t promise anything.

**Comment by thebspin** [comment] 2022-09-16 11:29
Thanks for you're response!
I will try and get it to a minimal repo to see what can be done about it.
I just went through the code and i've spotted that in the shared.js where we iterate over `programNode.body` we don't actually check that `programNode.body` body exists. This on it's own would solve the issue for me without breaking the codes for others. Maybe this is worth adding? Something like:

```
if(!programNode.body) return chucks;
```

What do you think about this?

**Comment by lydell** [comment] 2022-09-16 12:00
That could be worth doing if we find that it is the true solution. I won’t add it without understanding the problem.

**Comment by thebspin** [comment] 2022-09-16 13:22
I've tried it while debugging and it fixes the issue for me.
When the targeted file exist only of html, the body property does not exist on `programNode`.
It does contain a different propertyName (no longer have the debug open so not sure of the name) that contains all the HTML, but this plugin does not want to do anything with the HTML.

I would have made a PR if i know how to proper test this change, locally i could not make the succeed.

**Comment by lydell** [comment] 2022-09-16 13:33
I would like to know why the rule is run on HTML files in the first place before making any changes.

**Comment by thebspin** [comment] 2022-09-16 14:25
It's because the NX setup does something like this:

```
"lintFilePatterns": [
   "apps/bookingtool/src/**/*.ts",
   "apps/bookingtool/src/**/*.html"
]
```

And therefor the plugin also traverses the html files.
By making sure this plugin does not crash when there is no body you don't change anything to your current implementation but you also will make sure people that people who use eslint for html stuff will be able so use this plugin.

**Comment by lydell** [comment] 2022-09-16 14:43
That sounds like an endless whack-a-mole of issue reports to various ESLint plugins that their rules don’t work when run on files where they don’t make sense. Surely there must be a way to configure NX to run the correct rules for each file?

- It’s also bad for performance to run unnecessary rules.
- Myself I want slightly different rules for JS vs TS files, and I don’t think I’m alone there. So it feels like there must be a way to choose rules per file type anyway.

**Comment by thebspin** [comment] 2022-09-17 06:19
It's not NX it's 'fault' perse.
They just pass the argument to the eslint config itself and let eslint handle it.
In the eslint config you can do something like this:

```
"overrides": [
	{
		"files": ["*.html"],
		"rules": {
			"simple-import-sort/imports": "off"
		}
	},
]
```

But either this is not being respected or the problem is that the code for the plugin is always being run when imported inside your eslint config and therefor it runs against all the files it's being passed on from eslint.

**Comment by lydell** [comment] 2022-09-17 08:23
Then it looks like you’ve identified that NX does something wrong? I’d suggest reporting it to them: Show them how you configure some rules to do or do not apply to some file types and how that isn’t respected.

**Comment by thebspin** [comment] 2022-09-17 08:52
This is a not an NX problem/mistake. They just pass an argument to the eslint config to apply eslint to javascript and html when running the linter. The above example is from the eslint config itself, and i don't think the above example should fail because some eslint mistake but it does. 

Then again i am no eslint expert, but i do think above fix is the way to go so people can use eslint together with this plugin (that works amazingly btw and does everything i want it to do) for more then just js/ts files.

**Comment by lydell** [comment] 2022-09-17 09:43
Can you show me a more popular ESLint plugin (that is made for JavaScript or TypeScript, not HTML or markdown or Vue or whatever) than this one where all rules don’t crash if you enable them on non-JS or non-TS files? Including a repo or gist to prove it. If such plugins exist, it indicates that this plugin should mimic how they handle it.

**Comment by lydell** [comment] 2022-09-17 14:41
Here is my current understanding:

1. It is not reasonable to expect every single plugin in the ESLint ecosystem to implement fragile duck typing checks to see if they seem to run on a supported file type or not.
2. In an ideal world, ESLint itself would handle plugin and file type mismatches, but with how the plugin system has gradually grown to be I don’t think ESLint has that information.
3. So it’s on the user to configure ESLint correctly. Running a rule on a file type where it doesn’t make sense is simply undefined behavior. Your suggested change would make things worse by hiding the user error instead of at least giving some clue about it.

I’m going to close this since I don’t think there’s anything wrong with this plugin, but feel free to drop a comment if you find evidence that I’m wrong and I’ll reopen and re-think.

**Closed by lydell** 2022-09-17 14:41 UTC
