### ISSUE TITLE
Group for first party packages

### ISSUE THREAD

**Issue by Lexicality** [lydell/eslint-plugin-simple-import-sort#18] opened 2019-07-08 14:21 UTC
We have a module alias called `web` for our local code (like `@` in #4) and I'd like it to be sorted into it's own group like this:
```javascript
import React from "react"

import { Foo } from "web/components/foo"

import { Bar } from "./bar"
```
`import/order` supports this by doing a bunch of magic with Webpack parsing, but just having a list of first party packages as a config variable would be a lot easier.
Thanks

**Comment by lydell** [comment] 2019-07-08 16:12
Hi!

Like mentioned in https://github.com/lydell/eslint-plugin-simple-import-sort/issues/4#issuecomment-473649628, I’d recommend choosing an alias that does not look like an npm package name. I think that is less confusing as well. Would that work for you?

**Comment by Lexicality** [comment] 2019-07-08 18:56
Not really, no. Our project is very big and has a lot of people on it and I only recently managed to convince everyone that using the `web/` prefix is a good idea.
I don't think going back to them again and proposing we rewrite 400+ files to use `@/components` instead of `web/components` (especially when the file system is `src/web/components`) would be a popular move.

**Comment by lydell** [comment] 2019-07-08 19:17
Thanks for your reply. I understand that it would be inconvenient to make another such big change and have to re-teach everyone to use for example `@` instead of `web`.

On the other hand – if we did add an option for this you would still end up with 400+ files where the sorting changed?

I really want this plugin to stay free of options for as long as possible, because as soon as we add one it feels like opening the flood gates to more. And I’m not sure trying to parse webpack/Rollup/TypeScript/whatever configs is going to be sustainable.

¯\\\_(ツ)\_/¯

**Comment by Lexicality** [comment] 2019-07-08 19:41
There's a bit of a difference between me adding an additional rule to the automatic `eslint --fix` command that runs as a pre-commit hook to progressively improve the codebase and me convincing people to change how they write code (again). 😛

I entirely appreciate you not wanting to add more complexity to this plugin, and if you don't want to add it I will probably end up writing my own plugin. 🙂 

FWIW I think parsing any kind of config is way overkill. A `firstPartyPackages` option in eslint would do the job perfectly well.

**Comment by lydell** [comment] 2019-07-08 19:56
Hmm … could you add a custom little ESLint rule that autofixes from `web` to the new prefix then? Like `import { Foo } from "web/components/foo"` to `import { Foo } from "~web/components/foo"` or something maybe?

If you do write your own plugin then feel free to share it here!

**Comment by Lexicality** [comment] 2019-07-08 20:55
Well, admittedly using `~web` would match what you have to do inside stylesheets 🤔 (though knowing Webpack, we'd probably end up with `url("~~web/...")` in them after the change)

Ideally I'd want a plugin that just alphabetises imports by block and then let a different one (eg import/order) make the actual blocks, but I guess with the unknown order that eslint will apply rules in, that wouldn't be very stable.

**Comment by ystarlongzi** [comment] 2019-08-15 03:53
Allow custom prefixes, this is very helpful for developers, hope to support this feature.

@lydell

**Comment by ystarlongzi** [comment] 2019-08-15 03:54
Allow custom prefixes, this is very helpful for developers, hope to support this feature.

@lydell

**Comment by heygrady** [comment] 2019-09-05 20:24
Normally I use [`eslint-import-resolver-babel-module`](https://github.com/tleunen/eslint-import-resolver-babel-module) with `eslint-plugin-import`. That allows it to support this case. Of course, people use `eslint-plugin-simple-import-sort` because the import sorting PR for `eslint-plugin-import` has not merged (https://github.com/benmosher/eslint-plugin-import/pull/1360)

```js
  settings: {
    'import/resolver': {
      'babel-module': {
        root: ['./src/'],
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.d.ts'],
      },
  },
```

**Comment by lydell** [comment] 2019-09-06 05:48
@heygrady Don’t you think it’s confusing that some npm-package-looking imports actually resolve to local code? What’s your thought on my recommendation so far to use for example `@/` as a prefix?

**Comment by ystarlongzi** [comment] 2019-09-06 06:13
> Don’t you think it’s confusing that some npm-package-looking imports actually resolve to local code?

Use the [resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias) feature of webpack is very useful, otherwise you might import to some common code in the project like this:

``` javascript
import xx from '../../../utils/xx'
```

Actually, because of the webpack  support `resolve.alias` feature, the code maybe like this:

``` javascript
import xx from '@utils/xx'
```


> What’s your thought on my recommendation so far to use for example @/ as a prefix?

Suggest expose the configuration to allow developers to modify.

**Comment by lydell** [comment] 2019-09-06 06:23
Personally, I’ve always bit the bullet and used those super ugly `../../../` imports because it works out of the box with all tools and all editors that teammates use.

IMO, `@utils/xx` is not good either, because it looks like a scoped npm package (like `@babel/core`).

> > What’s your thought on my recommendation so far to use for example @/ as a prefix?
>
> Suggest expose the configuration to allow developers to modify.

Sorry, that’s not what I meant. What I meant is – if I say "The solution is to use a non-ambiguous prefix such as `@/`" (`@/utils/xx`) – how would you respond? Would you consider changing to that? If not – why not? Etc. I’m trying to get a more complete picture of people’s situations. "We’ve always done it that way" is not enough for me to make this plugin worse (IMO) by adding configuration that (IMO) is not needed.

**Comment by heygrady** [comment] 2019-09-10 06:00
I think the issue is that it's a very common practice. For instance, [absolute imports are supported by create-react-app](https://create-react-app.dev/docs/importing-a-component#absolute-imports).

There are some caveats with absolute imports (like name collisions with an existing npm package). However, it's not really valuable to bike-shed what people _should_ be doing. The important bit here is that people _are_ using absolute imports. It's supported by eslint, babel, rollup and webpack.

There is a non-zero set of people who use eslint and babel, use absolute imports for perfectly valid reasons, and who would also like to have their imports sorted.

It's worth noting that your plugin appears to do the "right thing" with `camelCasePaths`.

```js
import { foo } from 'absolute' // <-- in the wrong spot
import { bar } from 'npm-package'

import { baz } from 'absoluteCamelCase' // <-- in the right spot

import { foo } from './relative'
```

**Comment by lydell** [comment] 2019-09-10 15:00
Those are very good point.

**Comment by theKashey** [comment] 2019-09-12 05:41
Keep in mind -  _absolte imports_ are 100% "native" for TypeScript.

**Comment by lydell** [comment] 2019-09-14 18:23
Grouping idea:

1. Side effect imports.
2. Node.js core modules **and modules specified in `dependencies` and `devDependencies` of the package.json of your project.**
3. Everything else.
4. Relative imports.

So, instead of using [validate-npm-package-name](https://github.com/npm/validate-npm-package-name) to decide what should go in group 2, we use a list of Node.js core modules and look in the closest package.json.

Do you think it would work?

**Comment by theKashey** [comment] 2019-09-14 22:14
> Maybe we could look for directory names inside node_modules up the directory tree instead.

Would not for the `preact` case. However, `react` could be one of _Node.js core modules_, just name them _core modules_.

**Comment by lydell** [comment] 2019-09-15 07:01
Ah, good point. Looking inside `node_modules` wouldn’t work either in the case of aliases.

I won’t add `react` to “core modules”.

**Comment by theKashey** [comment] 2019-09-15 08:52
"Well known modules"? 
Actually it could be addressed from another point of view - "simple modules". Like `react` or `path` is a simple name, `components/Button` - is a complex. However `@material-ui/Button`, and `@UI/Button` would end in a one group. Which is not a bug, but could be a feature.

> Absolute path usually are _complex_ - `components/Button` or `redux/state/list`, while "packages" are usually _simple_ - `react`, `react-redux`. However - there are exception from both sides.

**Comment by lydell** [comment] 2019-09-15 08:57
“Well known modules” won’t solve the problem. Users can alias anything.

“Simple modules” unfortunately won’t work either. Some npm packages let you import from `fp-ts/lib/Either` and stuff.

Keep the ideas coming!

Some rough ideas I have:

- Re-use the resolver stuff from eslint-plugin-import.
- Let the user provide a function that lets you do whatever they you with the grouping. It might be a little annoying writing that function, but oh well.
- Wait for somebody to write the Ultimate Resolver Package™ and use that.

**Comment by lydell** [comment] 2019-09-16 12:21
What if we added a function option like this:

```js
// .eslintrc.js
module.exports = {
  // ...
  rules: {
    "simple-import-sort/sort": ["error", {
      transform: (from, filepath) => {
        return from;
      },
    }],
  }
};
```

- `from` is the string after `from` in imports:

   ```js
   import x from "..."
                  ^^^
   ```

- `filepath` is the absolute path to the file that the `from` comes from:

   ```
   /home/you/projects/some/file.js
   ```

- The return value is what eslint-plugin-simple-import-sort should use instead of the original `from` value when sorting.

This way you could for example inspect the passed `from` value and return `"@/" + from` in some cases to move stuff to another group.

So. If this existed – would it be useful to you? Would it be too much work implementing such a function? Feel free to post your `transform` function here for the sake of discussion.

**Comment by lydell** [comment] 2019-09-16 14:57
Another idea is to add support for tsconfig.json and jsconfig.json, like create-react-app. If you use TypeScript you probably already have a tsconfig.json. If you use JavaScript you’ll have to create a jsconfig.json if you use non-standard stuff, which is probably a good idea anyway.

**Comment by lydell** [comment] 2019-09-16 15:29
Or maybe I’m just over thinking this, and we should just add an option that is an array of package names, like @Lexicality suggested in the first place.

**Comment by lydell** [comment] 2019-09-17 07:28
I’ve made up my mind.

TypeScript is a big thing these days. If you use “absolute imports” with TypeScript, you _have_ to set it up in tsconfig.json, right? Otherwise TypeScript won’t understand your imports and give errors. So it would be really nice if eslint-plugin-simple-import-sort Just Works with TypeScript out of the box.

What about if you don’t use TypeScript? Well, the easiest thing for the plugin is to go with the jsconfig.json approach. Same thing, just another file name. As a bonus your imports will then work in VSCode as well. And there’s nothing stopping other editors and tools from reading jsconfig.json either. create-react-app already supports it, as mentioned.

Pros:

- Works out of the box with TypeScript.
- Adds no options to eslint-plugin-simple-import-sort, which makes it easier to say no to options in the future.
- Lets several tools use the same import config.

Cons:

- A little more complicated to implement than a simple option. But still doable.

---

This is the plan.

I think that we only need to look at `baseUrl` and `paths` in tsconfig.json/jsconfig.json. Correct me if I’m wrong!

I’m thinking that the logic will be something like this:

1. For each linted file:

   1. If the file name ends with `.ts` or `.tsx`, look for the closest tsconfig.json.
   2. Otherwise look for the closest jsconfig.json.

2. For each `import` in the linted file:

   1. See if a `paths` pattern matches the `from` part. If it does, try to figure out if it points to something in `node_modules` or not. This decides which group to put the import in.

   2. Otherwise, if there’s a `baseUrl` – find that directory and look into it. If the `from` part starts with something in that directory, treat the import as first party.

**Comment by theKashey** [comment] 2019-09-17 07:47
No objections.
> But it would be suuuper good to extract ts/jsconfig resolution logic into the separate package, so other libraries and solutions could reuse it. (could be done as a postprocess)

**Comment by lydell** [comment] 2019-09-17 07:50
Yeah, I’m currently researching if there are any packages already that do this. Maybe this one: https://github.com/dividab/tsconfig-paths

**Comment by lydell** [comment] 2019-10-25 15:57
Status update: Last time I looked at this, I couldn’t find any module that supports tsconfig.json _and jsconfig.json._ But maybe we don’t need to support jsconfig.json at all, because tsconfig.json might work for JS too: See https://github.com/prettier/prettier/pull/6702#issuecomment-546056379 and onwards.

**Comment by entropitor** [comment] 2019-11-06 14:57
@lydell Something good to now: I'm using absolute imports in typescript but I don't use the `paths` feature but the `baseUrl` feature so I reference everything as `src/...`. Would this be supported as well? 

Why not using https://github.com/lydell/eslint-plugin-simple-import-sort/issues/18#issuecomment-531502613 and allow aliasing certain modules in the config for this plugin?

**Comment by lydell** [comment] 2019-11-06 19:31
@entropitor Thanks for letting me know about `baseUrl` as well. If TypeScript allows that we should support it.

**Comment by lydell** [comment] 2019-11-13 16:40
I have a thing coming up that will allow customizing this. I’m still interested in supporting TypeScript out of the box, but I’ll open a new issue for that.

**Comment by Lexicality** [comment] 2019-11-13 19:52
Hi, sorry for not taking part in the discussion, I've been extremely busy lately.
I'm mostly in favour of using tsconfig.json, but as I mentioned before our project is very big and very old and has a lot of weird stuff in it - along with a mixture of Typescript and Javascript files.
Our `tsconfig.json` looks a bit like this:
```json
{        
    "allowJs": true,
    "baseUrl": "media",
    "paths": {
        "*": ["./*", "./web/lib/*"]
    },
}
```
With a file structure a bit like this:
```
media/
    img/
    blah/
    stuff/
    web/
        modules/
            aaaa.js
            bbbb.ts
            etc.js
        components/
            foo.ts
            bar.js
            example-file.ts
        lib/
            vendored-lib1/
                index.js
            vendored-lib2.js
```
And example-file.ts looking a bit like this:
```typescript
import React from "react";
import lib1 from "vendored-lib1";
import lib2 from "vendored-lib2";

import { Foo } from "web/components/foo";
import aaa from "web/modules/aaa";

import { Bar } from "./bar";
```

I'm not completely against our vendored libs becoming 1st party packages - but I'd sort of prefer them not to if possible.

Sorry for being unhelpful 😬

**Comment by lydell** [comment] 2019-11-13 20:17
You’ll be able to put your vendored libs anywhere you want with my upcoming thing.

**Comment by lydell** [comment] 2019-11-22 17:51
v5.0.0 has now been released with the `groups` option. See [custom grouping](https://github.com/lydell/eslint-plugin-simple-import-sort/tree/d1d59be47b08733990a8a62f7caf735cdad420f9#custom-grouping).

Example:

```json
{
  "rules": {
    "simple-import-sort/sort": [
      "error",
      {
        "groups": [
          ["^\\u0000"],
          ["^@?\\w"],
          ["^(web|vendored-lib)(/.*|$)"],
          ["^\\."]
        ]
      }
    ]
  }
}
```

The automatic tsconfig.json idea is tracked in: https://github.com/lydell/eslint-plugin-simple-import-sort/issues/31

**Closed by lydell** 2019-11-22 17:51 UTC
Labels: enhancement
