### ISSUE TITLE
Breaks with eslint-plugin-markdown

### ISSUE THREAD

**Issue by heygrady** [lydell/eslint-plugin-simple-import-sort#22] opened 2019-08-30 06:38 UTC
https://github.com/eslint/eslint-plugin-markdown

Parsed some markdown files and totally mangled them. Easy to turn off the rule for markdown but other rules (like `import/order`) seemed to manage the individual code blocks well.

**Comment by lydell** [comment] 2019-08-30 20:29
Hi! I've never used eslint-plugin-markdown before. Can you show me how you set things up? The best thing would be a small reproduction repo.

**Comment by heygrady** [comment] 2019-09-05 20:16
```js
module.exports = {
  extends: [],
  plugins: [
    'simple-import-sort',
    'markdown',
  ],
  settings: {
    'import/resolver': {
      'babel-module': {
        root: ['./src/'],
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.d.ts'],
      },
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.d.ts'],
      },
    },
    react: {
      version: 'Infinity',
    },
  },
  rules: {
    'simple-import-sort/sort': 'error',
  },
  overrides: [
    {
      files: ['**/*.md'],
      parserOptions: {
        ecmaFeatures: {
          impliedStrict: true,
        },
      },
      rules: {
        'simple-import-sort/sort': 'error',
      },
    },
  ],
}
```

```md
Some text

\\```js
import b from 'b'
import a from 'a'
\\```
```

**Comment by lydell** [comment] 2019-09-06 06:05
Couldn’t you have bothered to post something that actually works? 😢 

Anyway, after fighting ESLint’s configuration I finally made it work and could reproduce the issue.

`````md
Some text

```js
import b from 'b'
import a from 'a'
```
`````

is autofixed to:

`````md
import a from 'a'
import b from 'b'
```
`````

In other words, everything before the first `import` seems to be removed.

**Comment by lydell** [comment] 2019-09-07 07:11
Discovery: The issue only seems to occur when the autofix applies from the very beginning of the code block (index 0).

For example:

`````md
Some text

```js
;import b from 'b'
import a from 'a'
```
`````

successfully autofixes to:

`````md
Some text

```js
;import a from 'a'
import b from 'b'
```
`````

Feels like a bug in eslint-plugin-markdown. I need to investigate further.

**Comment by lydell** [comment] 2019-10-08 05:34
https://github.com/eslint/eslint-plugin-markdown/pull/119 has been merged, so the next version of eslint-plugin-markdown should not cause removals of markdown above imports anymore.

You might still run into https://github.com/eslint/eslint-plugin-markdown/pull/120, though.

**Comment by lydell** [comment] 2019-10-22 06:20
v1.0.1 of eslint-plugin-markdown has been released! All the above issues should be fixed.

I have some uncommitted test that I need to finish up, then we can close this issue.

**Closed** 2019-10-26 15:18 UTC
Labels: bug
