### ISSUE TITLE
bug: import { ,ofSubject } from 'rxjs';

### ISSUE THREAD

**Issue by chimurai** [lydell/eslint-plugin-simple-import-sort#33] opened 2019-12-08 19:24 UTC
Thanks for this awesome plugin.

Ran into this bug...
Using version `5.0.0`

Input:
```typescript
import { Subject, of } from 'rxjs';
```

Output:
```typescript
import { ,ofSubject } from 'rxjs';
```

**Comment by lydell** [comment] 2019-12-08 19:30
Hi!

When I tried to reproduce your issue, I got this:

```js
import { of,Subject } from 'rxjs';
```

There must be something different in your environment.

**Comment by chimurai** [comment] 2019-12-08 19:36
Thanks for the fast reply. 

That's interesting.

Using this eslint config:

```json
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "simple-import-sort", "prettier"],
  "extends": ["plugin:prettier/recommended", "plugin:@typescript-eslint/recommended"],
  "rules": {
    "simple-import-sort/sort": "error",
    "prettier/prettier": "error"
  }
}

```

**Comment by lydell** [comment] 2019-12-08 19:55
This seems to only happen when using the TypeScript parser.

This test case fails: https://github.com/lydell/eslint-plugin-simple-import-sort/compare/typescript-issue

**Comment by chimurai** [comment] 2019-12-08 20:03
I reduced it to this minimal typescript eslint config to reproduce it:

```json
{
  "plugins": ["@typescript-eslint", "simple-import-sort"],
  "extends": ["plugin:@typescript-eslint/recommended"],
  "rules": {
    "simple-import-sort/sort": "error"
  }
}

```

**Comment by lydell** [comment] 2019-12-08 20:04
Change `plugin:@typescript-eslint/recommended` into `plugin:@typescript-eslint/base` to make it even more minimal ;)

**Comment by chimurai** [comment] 2019-12-08 20:09
Just tested it with the even more minimal config (`plugin:@typescript-eslint/base`).

Still got the issue ...

Output:
```typescript
import { ,ofSubject } from 'rxjs';
```

```json
{
  "plugins": ["@typescript-eslint", "simple-import-sort"],
  "extends": ["plugin:@typescript-eslint/base"],
  "rules": {
    "simple-import-sort/sort": "error"
  }
}
```

**Comment by lydell** [comment] 2019-12-08 20:15
Yes, that’s what I meant.

**Comment by runspired** [comment] 2019-12-10 18:10
Also using the typescript parser and ending up with imports like this:

```ts
import { attr, belongsTo,hasMany } from Model from '@ember-data/model';
```

starting from:

```ts
import Model from '@ember-data/model';
import { attr, hasMany, belongsTo } from '@ember-data/model';
```

**Comment by lydell** [comment] 2019-12-10 18:21
@runspired I get this output:

```ts
import Model from '@ember-data/model';
import { attr, belongsTo,hasMany } from '@ember-data/model';
```

There must be something different in your environment.

**Comment by runspired** [comment] 2019-12-10 18:24
@lydell I realized it was likely a similar parser issue but with a related plugin: turning off `import/no-duplicates` resolved the issue and resulted in the output you pasted above.

**Comment by lydell** [comment] 2020-01-21 18:00
This is due to a bug in @typescript-eslint/parser. PR to fix it here: https://github.com/typescript-eslint/typescript-eslint/pull/1487

Once that’s merged and released, you should be able to update @typescript-eslint/parser to fix the problem, and I’ll add a test for it and close this issue.

**Comment by lydell** [comment] 2020-01-28 07:33
Upgrade to @typescript-eslint/parser 2.18.0 and your problem should be gone!

**Closed by lydell** 2020-01-28 07:33 UTC
Labels: bug

**Comment by chimurai** [comment] 2020-02-03 14:12
Issue is resolved. Thanks for the great work!
